---
title: "Lalonde"
author: "Rachael Caelie (Rocky) Aikens"
date: "12/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE, warning = FALSE, message = FALSE, echo = FALSE, fig.align = "center", cache.lazy = F)
library(RACplots)
library(optmatch)
library(DOS2)
library(tidyverse)
library(ggpubr)
library(mice)
library(stratamatch)
library(knitr)
library(ggplotify)
library(MatchIt)

theme_set(theme_light())
```

```{r}
lalonde.split <- split_pilot_set(lalonde, treat = "treat", pilot_fraction = 1/6)
```

```{r}
prognostic_model <- lm(re78 ~ age + educ + black + hispan + married + nodegree + re74 + re75, data = lalonde.split$pilot_set)

summary(prognostic_model)

prog_scores <- predict(prognostic_model, newdata = lalonde.split$analysis_set)

propensity_model <- lm(re78 ~ . - treat, data = lalonde)

prop_scores <- predict(propensity_model, newdata = lalonde.split$analysis_set)

a_set <- lalonde.split$analysis_set %>%
  mutate(prog = prog_scores,
         prop = prop_scores,
         t = treat) 
```

```{r}
AC_plot2 <- function(data, title = "", shaded_class = 1){
  if(shaded_class == "none"){
    plt_data <- data %>%
    mutate(t = as.factor(t),
           a = 0.9) %>%
    dplyr::select(c(t, prog, prop, a))
  } else{
     plt_data <- data %>%
      mutate(t = as.factor(t),
             a = ifelse(t == shaded_class, 0.9, 1)) %>%
      dplyr::select(c(t, prog, prop, a)) 
  }
  
  plt <- ggplot(data = plt_data, aes( x = prop, y = prog, group = t, color = t)) + 
    geom_point(size = 1, aes(alpha = a)) +
    scale_color_brewer(palette="Set1", direction = -1) +
    ggtitle(title) +
    theme(legend.position = "none", aspect.ratio=1, plot.title = element_text(hjust = 0.5, size = 9))+
    ylab(expression(paste("Prognosis, ", Psi, "(x)", sep = ""))) +
    xlab(expression(paste("Propensity, ", phi, "(x)", sep = "")))
  
  return(plt)
}
```

```{r}
AC_plot2(a_set, shaded_class = 2)
```

